apiVersion: v2
type: application
appVersion: v1.53.0
description: The reference implementation for a Matrix.org chat server
name: synapse
version: 0.9.0
keywords:
  - synapse
  - chat
  - matrix
  - riot
home: https://github.com/matrix-org/synapse
sources:
  - https://github.com/matrix-org/synapse
  - https://hub.docker.com/r/matrixdotorg/synapse
  - https://matrix.org/blog/home/
dependencies:
  - name: postgresql
    repository: https://charts.bitnami.com/bitnami
    version: ~10.3.17
    condition: postgresql.enabled
